// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
// Last generated at 21/11/2025 21:02:05

namespace Test
{
	public enum TestSfxEnum
	{
		NavigateButtonPositive = 0,
		ButtonNegative = 1,
		Error = 2,
		ItemConsumed = 3,
		Equip = 4,
	}
}
