// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
// Last generated at 10/09/2026 20:26:52

namespace Test
{
	public enum TestSfxEnum : ulong
	{
		/// <summary>Navigate-ButtonPositive</summary>
		NavigateButtonPositive = 12069975141896364794UL,
		/// <summary>ButtonNegative</summary>
		ButtonNegative = 15264754500189748758UL,
		/// <summary>Error</summary>
		Error = 6860172195720241041UL,
		/// <summary>ItemConsumed</summary>
		ItemConsumed = 4826419420261722300UL,
		/// <summary>Equip</summary>
		Equip = 3050062012289639731UL,
	}
}
