// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
// Last generated at 11/09/2026 20:40:44

namespace Test
{
	public enum TestMusicEnum : ulong
	{
		/// <summary>MusicSample</summary>
		MusicSample = 4609058388367795966UL,
	}
}
