// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
// Last generated at 06/10/2026 15:33:00

namespace Test
{
	public enum TestMusicEnum : ulong
	{
		/// <summary>MusicSample</summary>
		MusicSample = 4609058388367795966UL,
		/// <summary>MusicSample Sparse</summary>
		MusicSampleSparse = 7582811596174046190UL,
	}
}
