// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
// Last generated at 05/08/2026 21:07:37

using RPGFramework.Battle;
using System.IO;
using RPGFramework.Battle.Databases;
using UnityEngine;

namespace Test.Battle
{
	internal class BattleArenaDatabase : IBattleArenaDatabase
	{
		private readonly BattleArenaDefinition[] m_Arenas;

		internal BattleArenaDatabase()
		{
			string assetBundlesPath = Path.Combine(Application.streamingAssetsPath, "Battle");
			m_Arenas = new BattleArenaDefinition[]
			{
				new BattleArenaDefinition("Arena0", Path.Combine(assetBundlesPath, "arena0")),
			};
		}

		BattleArenaDefinition IBattleArenaDatabase.Get(int index)
		{
			return m_Arenas[index];
		}
	}
}
