// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
// Last generated at 16/08/2026 20:40:14

using RPGFramework.Field;
using RPGFramework.Hashing;
using System.Collections.Generic;
using System.IO;
using UnityEngine;

namespace Test.Field
{
	internal class FieldDatabase : IFieldDatabase
	{
		private readonly Dictionary<ulong, FieldDatabaseAsset> m_FieldsByNameHash;

		internal FieldDatabase()
		{
			string assetBundlesPath = Path.Combine(Application.streamingAssetsPath, "Field");
			m_FieldsByNameHash = new Dictionary<ulong, FieldDatabaseAsset>(3)
			{
				[Fnv1a64.Hash("TestField0")] = new FieldDatabaseAsset("TestField0", Path.Combine(assetBundlesPath, "testfield0"),
					new string[]
					{
						"Generic",
						"TestField",
					}
				),
				[Fnv1a64.Hash("TestField1")] = new FieldDatabaseAsset("TestField1", Path.Combine(assetBundlesPath, "testfield1"),
					new string[]
					{
						"Generic",
					}
				),
				[Fnv1a64.Hash("TestField2")] = new FieldDatabaseAsset("TestField2", Path.Combine(assetBundlesPath, "testfield2"),
					new string[]
					{
						"Generic",
						"TestField",
					}
				),
			};
		}

		FieldDatabaseAsset IFieldDatabase.Get(ulong fieldNameHash)
		{
			return m_FieldsByNameHash[fieldNameHash];
		}
	}
}
