// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
// Last generated at 15/08/2026 21:05:38

using RPGFramework.Field;
using System.IO;
using UnityEngine;

namespace Test.Field
{
	internal class FieldDatabase : IFieldDatabase
	{
		private readonly FieldDatabaseAsset[] m_Fields;

		internal FieldDatabase()
		{
			string assetBundlesPath = Path.Combine(Application.streamingAssetsPath, "Field");
			m_Fields = new FieldDatabaseAsset[]
			{
				new FieldDatabaseAsset("TestField0", Path.Combine(assetBundlesPath, "testfield0"),
					new string[]
					{
						"Generic",
						"TestField",
					}
				),
				new FieldDatabaseAsset("TestField1", Path.Combine(assetBundlesPath, "testfield1"),
					new string[]
					{
						"Generic",
					}
				),
				new FieldDatabaseAsset("TestField2", Path.Combine(assetBundlesPath, "testfield2"),
					new string[]
					{
						"Generic",
						"TestField",
					}
				),
			};
		}

		FieldDatabaseAsset IFieldDatabase.Get(int index)
		{
			return m_Fields[index];
		}
	}
}
